services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: ["npm", "start"]